version: "3.9"
services:
  db:
    image: postgres:15
    container_name: workflow-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workflow
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
